### ISSUE TITLE
No longer seems to support loading style via e.g. kvirc.exe" -stylesheet=style.css

### ISSUE THREAD

**Issue by ltc-data** [kvirc/KVIrc#2229]
### Expected behavior
Use to support via shortcut loading a stylesheet 
e.g ```"C:\Program Files\KVIrc\kvirc.exe" -style=style.css```
The provided style use to color the tooltips for instance.

### Actual behavior
Style seems to be ignored completely as of late.

[//]:# (Besides the text description, include any screenshots that help us visualize the issue you're facing)

### Steps to reproduce the issue
1. On Windows 7 for instance create a style.css with contents below
2. load file below.via shortcut
3. observe

```css
/* Customize tooltips. */
QToolTip {
    background-color: rgb(252,252,210);
    border-color: darkslategray;
    border-width: 1px;
    border-style: solid;
    padding: 2px;
    border-radius: 7px;
    opacity: 255;
}
```
Edit (uploading style did not work. :(
Other thoughts.
Checked Qt 5.8.0 supports QToolTip

### System information
[//]:# (Type ```/about.kvirc``` or click "Help → About KVIrc" and copy & paste the details from the "Executable Information" tab below between ``` marks)  
[//]:# (Also Enter any OS information the "Executable Information" tab doesn't contain, e.g. KDE, Gentoo, Linux Mint, etc.)

```
KVIrc 4.9.2 'Aria'

Runtime Info:
System name: Windows Release : 6.1.7601
System version: Windows 7 Ultimate (x64) Service Pack 1 (Build 7601)
Architecture: Intel64 Family 6 Model 158 Stepping 9
Qt version: 5.8.0
Qt theme: windowsvista

Build Info:
Build date: 2017-06-01 13:25:16 UTC
Sources date: 20170601
Revision number: git-7115-g2c89201e3
System name: Windows-6.3.9600
CPU name: AMD64
Build command: C:/Program Files (x86)/CMake/bin/cmake.exe
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=C:/projects/kvirc/build/release
   Threads=Win32
Compiler name: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe
Compiler flags: /DWIN32 /D_WINDOWS /W3 /GR /EHsc
Qt version: 5.8.0
Features: IRC, IPv6, Crypt, SSL, IPC, Transparency, Perl, Python, Enchant, Qt5, KVS
```
[//]:# (If you experienced crashes or segfaults please also include a stacktrace below, For how-to read: https://github.com/kvirc/KVIrc/wiki/Grabbing-a-useful-backtrace.)
